apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: create-deployments-services
  namespace: default
rules:
- apiGroups: ["apps", ""]
  resources: ["deployments", "deployments.apps", "services"]
  verbs: ["get", "list", "watch" , "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-deployments-services-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: create-deployments-services
subjects:
  - kind: ServiceAccount
    name: wild-west-k8s-sa
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: view
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default