apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: wild-west-k8s-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/danielhelfand/wild-west-kubernetes #configure: may change according to your source